[project]
name = "ansible-role-osx-terminal-themes"
version = "0.0.0"
requires-python = ">=3.12"

[dependency-groups]
dev = [
  "ansible",
  "ansible-lint",
  "flake8",
  "pre-commit",
  "yamllint",
]
