---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'brianhartsock.osx_terminal_themes'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'brianhartsock.osx_terminal_themes'

      - name: Set up uv.
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies.
        run: uv sync

      - name: Ansible lint
        run: uv run ansible-lint

      - name: YAML lint
        run: uv run yamllint .

      - name: Python lint
        run: uv run flake8
