name: Publish Role to Galaxy

on: # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up uv.
        uses: astral-sh/setup-uv@v5

      - name: Install Ansible.
        run: uv tool install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
